# This file was generated by GoReleaser. DO NOT EDIT.
class Restish < Formula
  desc "Restish is a CLI for interacting with REST-ish HTTP APIs with some nice features built-in."
  homepage "https://rest.sh/"
  version "0.4.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/danielgtaylor/restish/releases/download/v0.4.5/restish-0.4.5-mac-x86_64.tar.gz"
    sha256 "028f185f956acd7d408f209e20c561a096b54e015b5ebc1f4de3b95b473dfcc5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/danielgtaylor/restish/releases/download/v0.4.5/restish-0.4.5-linux-x86_64.tar.gz"
    sha256 "4fb759e1e086d3e579f1fa1fc6efdd6602187ac4d1dddc74695d4fced97549d5"
  end

  def install
    bin.install "restish"
  end
end
