# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restish < Formula
  desc "Restish is a CLI for interacting with REST-ish HTTP APIs with some nice features built-in."
  homepage "https://rest.sh/"
  version "0.13.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/danielgtaylor/restish/releases/download/v0.13.1/restish-0.13.1-mac-arm64.tar.gz"
      sha256 "95090183903b4d33a3134bbf372b88bc870072de4379d97c62965bdad8d8fe4a"

      def install
        bin.install "restish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/danielgtaylor/restish/releases/download/v0.13.1/restish-0.13.1-mac-x86_64.tar.gz"
      sha256 "7075c3648d8fe9503950718770310b3ecfba8c6a844f09b490b1615c75190919"

      def install
        bin.install "restish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/danielgtaylor/restish/releases/download/v0.13.1/restish-0.13.1-linux-x86_64.tar.gz"
      sha256 "9ef511e04e4194c89ca8c62480f0f63ebdc9f2ad2555fff9d2bae37a36fada47"

      def install
        bin.install "restish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danielgtaylor/restish/releases/download/v0.13.1/restish-0.13.1-linux-arm64.tar.gz"
      sha256 "d6dca1169861fd09e1b41fa9ff93191a0ddae118486d387d3e50d6a33066324f"

      def install
        bin.install "restish"
      end
    end
  end
end
